### ISSUE TITLE
Cannot launch the script

### ISSUE THREAD

**Issue by Keiishu** [noisemaster/airhornbot#2]
I did `npm install`, then I tried `npm run start` and it seems that the config module is missing, or else I did not installed it properly.

Here is the error : 
```pi@raspberrypi:~/airhornbot $ npm run start

> aurhonbort@1.0.0 start /home/pi/airhornbot
> node app.js

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module './config'
Require stack:
- /home/pi/airhornbot/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/airhornbot/app.js:4:26)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/airhornbot/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aurhonbort@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aurhonbort@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

[2019-07-29T23_14_23_496Z-debug.log](https://github.com/noisemaster/airhornbot/files/3444554/2019-07-29T23_14_23_496Z-debug.log)

Is there anything I did wrong?

**Comment by noisemaster** [comment]
I should've put this in the readme but the bot looks for the Discord bot token in a json file called `config.json`. This file should be put in the same folder as app.js with the following format.

```json
{
    "discordToken": "your bot token from Discord"
}
```

**Comment by Keiishu** [comment]
Okay it works perfectly, thank you :D
