### ISSUE TITLE
} missing

### ISSUE THREAD

**Issue by Keiishu** [noisemaster/airhornbot#4]
```> aurhonbort@1.0.0 start /home/pi/airhornbot
> node app.js

/home/pi/airhornbot/app.js:14
  bot.editStatus({name: botStatus, type: botStatusType)
                                                      ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aurhonbort@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aurhonbort@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Keiishu** [comment]
#5
